### ISSUE TITLE
Estrutura dos dados

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#1]
@tamielbr , Estou criando as tabelas do CiclopeDB, e vieram alguns pontos

1) Atributos das tabelas: fiz uma lista preliminar (baseados nos json e nos dados que você conseguiu via LAI): https://github.com/gabrielfedel/CiclopeDB/blob/master/uab/db/descricao.md

Pode dar uma olhada pra ver se tem algo que entra ou sai?

2) Estou um pouco confuso na relação do curso, com as outras "entidades". Estou considerando que temos ipes, polos e cursos.
Minhas dúvida são as seguintes:
- o curso está relacionado ao polo somente? ou ele é ligado à ipes também ?( um curso x é oferecido via polo a pela ipes b)
- outra coisa, você acha que tratamos os cursos como únicos? por exemplo, se tiver pedagogia no polo a e no polo b, são 2 cursos diferentes? ou é o mesmo curso, com duas ofertas distintas?

A maior parte dessas coisas eu posso mudar depois, mas já sabendo facilita na implementação

**Comment by tamielbr** [comment]
@gabrielfedel conversamos já sobre essa né? Podemos fechar?

**Comment by gabrielfedel** [comment]
Opa sim.

**Comment by gabrielfedel** [comment]
@tamielbr , eu acho que eu não anotei e agora fiquei em dúvida se vamos utilizar todos os dados que estão csv exportado da CAPES em relação à oferta de cursos. Os campos à seguir eu não havia utilizado, mas pela outra issue acho que a ideia é utilizar né? Vou inserir todos eles na tabela, e vemos quais utilizamos ok?

dt_inicio_real_oferta_14  
dt_provavel_fim_15  
dt_fim_curso_16 
qt_vagas_17 
qt_alunos_formado_18  
qt_alunos_nao_concluinte_19 
qt_alunos_desvinculado_20  
qt_alunos_cadastrado_21

**Comment by tamielbr** [comment]
@gabrielfedel legal seguir a outra. qq coisa ajustamos...
