### ISSUE TITLE
Texto de introdução UAB

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#10]

**Comment by tamielbr** [comment]
Esclarecer:
- Só incluímos dados de polos ativos (nos dois casos)
- Removemos os cursos que não tiveram oferta real de início

**Comment by tamielbr** [comment]
@gabrielfedel fiz uma nova versão apontando para o `css` correto, mas no caso do `sobre.html` ainda há erro nos gráficos (não aparecem). Não consegui entender porque, mas vi que o chart depende dos dados do mapa (a função está dentro da função que cria o mapa). Talvez seja fácil simplificar esse código?

**Comment by gabrielfedel** [comment]
foi
