### ISSUE TITLE
Dados de oferta de cursos em polos não cadastrados

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#12]
Existem dados de oferta de cursos em polos não estão nos dados que temos, posso desconsiderar esses dados?

**Comment by gabrielfedel** [comment]
Acabei de verificar que são de polos inativos, posso retira-los né?

**Comment by gabrielfedel** [comment]
Os dados de oferta de cursos estão associados à polos: ativos, desligados, inativos e provisório. Queremos somente os ativos?

**Comment by gabrielfedel** [comment]
Eu fiz um teste tentando inserir somente os ativos, mesmo assim tem 2 polos que não estavam nos dados da LAI, com id 760 e 1068, alguma ideia do que fazemos em relação à eles? excluímos? usamos os dados que estão disponíveis no csv que exportou?

**Comment by tamielbr** [comment]
acho que podemos ir com os dados mais atuais. podemos focar nos ativos somente.
