### ISSUE TITLE
O quê define a associação IPES -> Polo

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#16]
A relação ipes polo é definida pela oferta do curso. 
Se uma ipes ofertou um curso para um polo alguma vez (mesmo que não oferte mais), esse polo continua "associado" à IPES?

**Comment by tamielbr** [comment]
sim, no sentido que o quando clicarmos no polo, queresmos ver no datatables a lista com os cursos já ofertados lá (ao longo do tempo) e que quando clicamos na IPES queremos ver os polos com os quais ela já se relacionou. é isso?

**Comment by gabrielfedel** [comment]
Isso mesmo. só pra confirmar mesmo, me bate a dúvida, por ser uma informação temporal.
