### ISSUE TITLE
Dados dos polos

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#19]
Definir os dados que serão exibidos dos polos:
-Datatables
-Gráfico

**Comment by gabrielfedel** [comment]
@tamielbr , quais dados vamos exibir dos polos?
-Cursos ofertados em datatables
-Algum gráfico?

**Comment by gabrielfedel** [comment]
![captura de tela - 24-03-2016 - 15 13 56](https://cloud.githubusercontent.com/assets/2080121/14026755/1d3186ba-f1d3-11e5-873e-3ee2dda65c0d.png)

@tamielbr que dados vamos exibir no datatables além do nome e tipo de curso?

**Comment by tamielbr** [comment]
O que aparece do polo deve ser o mesmo da IPES, só que pela perspectiva do polo. Na aba inicial, queremos os dados básicos do polo e um gráfico mostrando a distribuição regional. Seria legal mostrar algumas coisas, mas vai depender da dificuldade/tempo de implementação. O mais básico que queremos é o que você já fez:
1.  Estados das IPES que ofereceram cursos no polo (porcentagem)

Seria legal ter algo resumindo outras coisas básicas que a tabela tem e pode ser de fácil visualização na aba inicial, algo como um resumo.
1. Gráfico de barra com nomes das IPES e cursos que já ofereceu no polo (quantos cursos, por exemplo a UFRJ ofereceu, quantos a UFF, etc.)
2. Vagas ofertadas versus alunos formados (poderia ser barra, por ano)
3. Gráfico pizza com porcentagem por nível de curso (licenciatura, etc.) e número total de cursos por nível.

Em termos de dados é um espelho daquilo que montamos para a IPES, só que na perspectiva dos polos. Se não me engano, olhando para a tabela, era isso:
- Curso
- IPES ofertante
- Nível (licenciatura, etc.)
- Data da oferta
- Vagas oferecidas
- Alunos formados 
- Alunos desistentes

**Comment by gabrielfedel** [comment]
Certo.

Sobre esse:
Estados das IPES que ofereceram cursos no polo (porcentagem)

Não ficou muito claro pra mim. O gráfico que temos na IPES mostra quantos polos tem por estado daquela IPES específica. No caso de um polo, qual informação seria mostrada no gráfico de pizza? Quantidade de oferta de cursos ?

Sobre os outros gráficos vou verificar a dificuldade pra eles e confirmo, não tenho certeza se teremos tempo pra fazer os 3.

E sobre o datatables vou acertar desta maneira

**Comment by tamielbr** [comment]
sim - seria um gráfico de pizza com quais IPES ofereceram cursos no polo (porcentagem de cursos).

**Comment by gabrielfedel** [comment]
@tamielbr alunos desistentes = qt_alunos_nao_concluintes ? ou qt_alunos_nao_concluintes+qt_alunos_desvinculados ?

**Comment by tamielbr** [comment]
@gabrielfedel pra ficar claro para quem acessar, eu diria que: 
**Alunos não concluíntes** = `qt_alunos_nao_concluintes` + `qt_alunos_desvinculados`

Vendo a tabela, a soma parece ser ser correta. A soma de:
`qt_alunos_nao_concluintes` + `qt_alunos_desvinculados` = `qt_alunos_cadastrado`

Confere?

**Comment by gabrielfedel** [comment]
Acho que alunos não concluintes fica melhor mesmo

só pra corrigir
qt_alunos_cadastrados = qt_alunos_nao_concluintes + qt_alunos_desvinculados + qt_alunos_formados

**Comment by gabrielfedel** [comment]
datatables corrigido, gráfico 1 dos polos rodando

**Comment by tamielbr** [comment]
1. @gabrielfedel adicionar os dados de `qt_alunos_cadastrado` e a sequência:
2. Mudar visualização para a ordem: Vagas ofertadas -> Alunos cadastrados -> Formados -> Não concluintes.
3. Remover os dados vazios (sem data real de início)

**Comment by gabrielfedel** [comment]
Feito
