### ISSUE TITLE
Correção ortográfica geral

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#23]
Posso te ajudar com isso , nos acentos e cedílhas (por exemplo: `praça` versus `praca`). Não acho que foi problema de import, deve ser porque os dados vieram assim mesmo, não é? Não é crítico, mas se for rápido, talvez num encontro a gente resolva rapidamente. 

![screen shot 2016-03-24 at 16 59 32](https://cloud.githubusercontent.com/assets/3904166/14029607/d49f2e3e-f1e1-11e5-8392-1b40fe68a74e.png)

![screen shot 2016-03-24 at 17 00 46](https://cloud.githubusercontent.com/assets/3904166/14029634/fb9d0c2c-f1e1-11e5-8974-1b87647b0b05.png)

**Comment by gabrielfedel** [comment]
É os dados vieram assim mesmo. Não sei quão rápido pode ser (estou pensando se é melhor mexer com isso no csv ou direto no código de inserção do sql). Mas podemos deixar pra ver isso juntos mesmo

**Comment by tamielbr** [comment]
Deve vir via CAPES no futuro.
