### ISSUE TITLE
Datatables não é limpo/atualizado quando se clica em uma IPES que não tem dados para ele

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#29]

**Comment by gabrielfedel** [comment]
Na verdade a UFAC não tem cursos, e não tem polos mesmo. Pelo menos não nos dados que estamos utilizando.

O quê estava acontecendo é que não estava sendo limpo o datatables e ficavam os dados da ipes clicada anteriormente

**Comment by gabrielfedel** [comment]
Feito
