### ISSUE TITLE
Mudar lat/lon da UFT/UNITINS

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#31]
UFT = http://www.openstreetmap.org/way/260662589#map=19/-10.15671/-48.34986
UNITINS = http://www.openstreetmap.org/node/2601482061#map=19/-10.19070/-48.31658

**Comment by tamielbr** [comment]
- UPE - http://www.openstreetmap.org/search?query=Avenida%20Agamenon%20Magalh%C3%A3es%2C%20recife#map=19/-8.04408/-34.88605
- UNIFESP (Sena) - http://www.openstreetmap.org/search?query=unifesp#map=19/-23.59184/-46.64877
- UNESP (SP) - http://www.openstreetmap.org/way/177664943#map=19/-23.59104/-46.61015
- UFTPR (mudar endereço REITORIA Av. Sete de Setembro, 3165 - Rebouças CEP 80230-901 - Curitiba - PR - Brasil), http://www.openstreetmap.org/way/24776063#map=18/-25.43958/-49.26862
- UFAL - http://www.openstreetmap.org/way/37060474#map=16/-9.5532/-35.7733
- UDESC - http://www.openstreetmap.org/search?query=udesc#map=18/-27.58481/-48.50266
- FIOCRUZ - http://www.openstreetmap.org/way/331141630#map=16/-22.8767/-43.2446
- IFRR - http://www.openstreetmap.org/node/2660062195#map=19/2.81362/-60.69447
- UFPI - http://www.openstreetmap.org/way/403860985#map=17/-5.05794/-42.79635
- IFSUL - http://www.openstreetmap.org/way/250310694#map=18/-31.76658/-52.35226
- IFPB - http://www.openstreetmap.org/way/379214130#map=19/-7.00422/-34.83417
- IFPA - http://www.openstreetmap.org/way/362775678#map=18/-1.43790/-48.46133
- IFMT - http://www.openstreetmap.org/way/154966272#map=18/-15.59211/-56.09827
- UEMA - http://www.openstreetmap.org/way/84198013#map=17/-2.57830/-44.20801
- IFMA - http://www.openstreetmap.org/way/137478279#map=18/-2.53377/-44.28783
- UEMS - http://www.openstreetmap.org/node/2104257641#map=19/-22.19699/-54.93047
- UERN - http://www.openstreetmap.org/way/260156733#map=19/-5.18942/-37.33991
- UECE - http://www.openstreetmap.org/way/158046051#map=18/-3.79437/-38.55619
- UFC - http://www.openstreetmap.org/way/329563200#map=19/-3.74549/-38.57574
- UFAM - http://www.openstreetmap.org/way/230379261#map=18/-3.09932/-59.97483
- UNCISAL - http://www.openstreetmap.org/way/48555227#map=18/-9.67384/-35.75850

**Comment by gabrielfedel** [comment]
Feito
