### ISSUE TITLE
Acertar lat/lon de todas as IPES corretamente

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#33]

**Comment by tamielbr** [comment]
@gabrielfedel pra deixar isso meio que organizado, poderíamos colocar isso num ethercalc ou num drive em formato de planilha, com a marcação das que estão feitas corretamente, e podemos deixar issso colaborativo. Seria um primeiro passo, e podemos fazer isso até o lançamento "oficial" depois do feedback do pessoal. que tal?

**Comment by gabrielfedel** [comment]
Legal, podemos fazer assim sim

**Comment by tamielbr** [comment]
@gabrielfedel conseguiu jogar numa planilha? Posso começar.

**Comment by gabrielfedel** [comment]
Opa: https://docs.google.com/spreadsheets/d/1YfHpewh2WjXJctP-Ka31ptakyxx_75mGccpREPKNIt8/edit?usp=sharing

Compartilhei com você, veja se rolou

**Comment by tamielbr** [comment]
Foi. Valeu. Vou deixar aberto até que fique com os dados completos.

**Comment by tamielbr** [comment]
Deve vir via CAPES.

**Comment by tamielbr** [comment]
Vai para V2.
