### ISSUE TITLE
Bug no Gráfico (mudança de tab)

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#34]
Quando se está em uma ipes em uma aba diferente da primeira, e muda-se para outro e vai para a aba de dados, o gráfico está com problema

**Comment by gabrielfedel** [comment]
Consegui uma solução, mas sempre manda pra primeira tab quando muda de polo
Pode ser assim @tamielbr

**Comment by tamielbr** [comment]
podemos ter como solução temporária, deixamos isso aberto como bug?

**Comment by gabrielfedel** [comment]
Está resolvido, porém sempre manda para a primeira aba, no caso que esteja em outra aba e mude de polo/ipes

**Comment by tamielbr** [comment]
@gabrielfedel funciona. Por um lado é bom porque volta pra aba informativa, por outro, pra quem tá querendo navegar/comparar é estranho. Vamos aguardar feedback pra ver se é problema.
