### ISSUE TITLE
Transferir projeto beta para servidor do Educação Aberta

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#35]
Depois do beta, vamos passar para o servidor e criar banco de dados

**Comment by tamielbr** [comment]
@gabrielfedel o pessoal aprovou. Podemos migrar? Me oriente sobre o que precisamos e eu posso arrumar aqui, pode ser?

**Comment by gabrielfedel** [comment]
Opa blz!
Ó o jeito mais simples é colocar os arquivos no servidor, e subir a base de dados (os sql estão todos atualizados em uab/db/ 
precisa executar o createtables.sql e os inserts na ordem: ipes, cursos, polos, oferta

Se você tiver acesso via terminal ao servidor,o ideal seria dar um git pull lá, pois quando precisarmos atualizar coisas, é só dar um novo pull que ele atualiza automaticamente

Se precisar de ajuda dê um toque

**Comment by tamielbr** [comment]
@gabrielfedel legal, vai ser no ASO. Creio que é tranquilo, vou tentar ver isso no finde. Me dá um comando pra facilitar? ;)

**Comment by tamielbr** [comment]
Feito: http://uab.educacaoaberta.org/
