### ISSUE TITLE
Mapa (JSON) demora para load

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#37]
Será que tem como pedir para pins demorarem , até mapa aparecer? Senão, eu ia sugerir remover esse e usar o JSON mais simples do mapa do brasil. Talvez seja detalhado demais.

**Comment by gabrielfedel** [comment]
Fiz uma modificação que ele só carrega os pins quando o mapa tiver terminado de carregar.
Acho que o motivo da grande demora é principalmente por causa do pingtime do meu servidor

veja o quê acha @tamielbr

**Comment by tamielbr** [comment]
Funcionou bem aqui. Depois testamos a velocidade no servidor do EdAb, mas acho que fechou.
