### ISSUE TITLE
Página com dados gerais da UAB

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#4]
Linha do tempo UAB
Datatables com todos os cursos/polos/neads
Gráficos com dados de NEADs e polos/distribuição

**Comment by tamielbr** [comment]
Etapa final, fazer em Json.

**Comment by tamielbr** [comment]
Cancelado, voltou pro Ciclope.

**Comment by tamielbr** [comment]
Quando clicar no "sobre", abre uma aba comum. Na principal, os dados gerais da UAB. Na tabela o dump completo de dados, na linha do tempo, a linha já pronta,.

**A fazer**
Datatables com dados completos (JSON)
Chart polos por estado
Chart polos por região

**Já feito**
Linha do tempo 
Chart NEAD por estado
Chart NEAD por região

**Comment by tamielbr** [comment]
@gabrielfedel está ligado ao #10, que já avancei. Vendo agora, seria legal ter os charts dos polos, como totais. Mas não sei se isso é trabalho demais. Veja o que acha. Quando a ter um datatables completo, acho que pode ser demais.

**Comment by tamielbr** [comment]
@gabrielfedel conseguimos fechar essa? Só dá um update quando puder e podemos criar outro issue com "wishlist" mais atualizado com o que não deu pra fazer, poe ser?

**Comment by gabrielfedel** [comment]
Opa Tel, achei que esse estava fechado. Só pra confirmar, sua sugestão é trocar os dois gráficos pelos dados de polos e não de ipes, é isso?

**Comment by tamielbr** [comment]
Pensei que adicionar um resumão dos polos, como já temos lá das IPES. Tinhamos falado de avaliar a quantidade de trabalho, se valia a pena. Senão, fica pra próxima e fechamos. Uma outra, que não sei se é fácil - colocar o valor total de IPES do lado da pizza.
