### ISSUE TITLE
Aba "segura" linha do tempo

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#43]
@gabrielfedel  - Clique em uma IPES com linha do tempo (e.g. UFPA/UFSC) e depois clique em qualquer polo. A linha do tempo (aba) se mantem).

**Comment by greevin** [comment]
Estou utilizando o Jquery UI nas abas em vez de usar 'gambiarra' para poder fazer a troca entre eles. Com isso, o plugin oferece uma solução para sempre deixar uma aba ativa mesmo que eu aperte outro ponto, ou seja, mesmo que eu clique em 'Linha do Tempo' e mude para outro IPES, a aba sempre volta para 'Dados Gerais'.
