### ISSUE TITLE
Revisão de dados

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#44]
@gabrielfedel estou olhando dados aleatoriamente para garantir que temos os dados corretos. Olhando por exemplo, o polo número 385, _CAPANEMA - SAO PEDRO E SAO PAULO_

Os dados dizem que temos no curso _EDUCACAO EM DIREITOS HUMANOS_ temos 7 não concluintes e 33 desvinculados, o que dão o total correto de 40 de alunos cadastrados. Lembro que falamos que a soma `qt_alunos_formado_18 + qt_alunos_nao_concluinte_19 +qt_alunos_desvinculado_20` = `qt_alunos_cadastrado_21`. 

Agora no site, colocamos `qt_alunos_nao_concluinte_19 + qt_alunos_desvinculado_20` = `alunos não concluintes` para facilitar. O problema é que, como vemos nesse do CAPANEMA, os dados não somam porque os **7** não concluintes não estão somados aos **33**.

![screen shot 2016-05-23 at 11 02 17](https://cloud.githubusercontent.com/assets/3904166/15473469/99a9d652-20d6-11e6-8374-bb0ff0c9935c.png)

É erro ou me perdi em algumas das nossas discussões?

**Comment by gabrielfedel** [comment]
@tamielbr , tinha um erro no código, não estava sendo somado os dados de não concluintes para os polos (só para as ipes), já corrigi é só dar um git pull pra atualizar
