### ISSUE TITLE
Gráfico das IPES nos polos sumiram

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#45]
@gabrielfedel -> Ao clicar num polo, o gráfico das IPES sumiram (na principal). Deve ser relacionado a mudanças no #44.

![screen shot 2016-05-26 at 16 24 31](https://cloud.githubusercontent.com/assets/3904166/15587208/944067e6-235e-11e6-9b86-624c18c4466f.png)

**Comment by gabrielfedel** [comment]
@tamielbr , aqui está aparecendo, me confirma o endereço onde está hospedando pra eu verificar se tem alguma coisa diferente?

**Comment by tamielbr** [comment]
@gabrielfedel  - Voltou... deve ser refresh do Firefox. Dei alguns na hora, abri e fechei browser, mas agora voltou. Valeu! Pra referência é (http://uab.educacaoaberta.org/).
