### ISSUE TITLE
Implementar módulo de busca 

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#47]
Atualmente o usuário não consegue fazer buscas por nada no mapa.

Queremos permitir busca por string e indicação no mapa da localização (algum destaque) do ponto selecionado (polo ou Núcleo/IPES). 

Veja modelo de implementação em http://afyamap.org, e plugin sugerido em http://labs.easyblog.it/maps/leaflet-search/

**Comment by kalimar** [comment]
https://www.mapbox.com/mapbox-gl-js/example/filter-markers-by-input/

**Comment by greevin** [comment]
Adicionei a busca apenas por IPES, por enquanto. Ao pesquisar, ele esconde os outros pins que não estão relacionados e, com isso, ele só mostra o que está sendo buscado. Ao apertar o X do lado da caixa de busca, ele limpa o resultado e volta a mostrar todos os pins novamente.

![tes](https://user-images.githubusercontent.com/7833013/37705527-177deb1a-2cdb-11e8-809c-e97ddee31801.png)

**Comment by tamielbr** [comment]
Entrei agora e não vi, já subiu?

**Comment by greevin** [comment]
Pronto, agora eu subi.

**Comment by tamielbr** [comment]
Funcionou show no Chrome. Mas Safari:

Não aparece lupa -> ![screen shot 2018-03-21 at 08 45 53](https://user-images.githubusercontent.com/3904166/37708154-5b429c5c-2ce4-11e8-95f2-c5990caa2f5e.png)

Caixa não expande -> ![screen shot 2018-03-21 at 08 45 57](https://user-images.githubusercontent.com/3904166/37708153-5b1c5ce0-2ce4-11e8-835c-2f103d4c4a2d.png)

**Comment by greevin** [comment]
Que estranho, no meu Safari funcionou sem problemas, mesmo no 'Modo Privado'.

![tssd](https://user-images.githubusercontent.com/7833013/37708349-1ca3d802-2ce5-11e8-8c66-58bb38d6b14c.png)

**Comment by gabrielfedel** [comment]
@tamielbr não é problema de cache?
Tentou no modo privativo?

**Comment by tamielbr** [comment]
Era. Resolvido ;)

**Comment by tamielbr** [comment]
@greevin aqui também só falta incluir polos não é?

**Comment by greevin** [comment]
A busca foi melhorada e foi incluído os polos na busca. Como sugestão do @kalimar, foi adicionado um autocomplete que auxilia na busca e, quando clicado, ele mostra o ponto no mapa.

**Comment by tamielbr** [comment]
Acho que tá funcionando muito bem. Considero fechada,  reabram se for o caso.
