### ISSUE TITLE
Implementar responsivo

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#49]
Sugere-se um modelo onde o mapa tome conta da tela toda. Ao clicar em um polo ou IPES, uma janela se abre em toda a tela (com ``x`` para fechamento) que contenha todos os dados da aba tradicional (veja que ``datatables`` já foi implementado com responsivo).

**Comment by tamielbr** [comment]
@greevin podemos fechar? Parece tudo ok.

**Comment by greevin** [comment]
@tamielbr Sim, caso seja necessário realizar alguma outra alteração, é só abrir outras issues.
