### ISSUE TITLE
Substituir menu de página inicial

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#50]
Seguindo a mudança #59, substituir menu por um ícone de ``home`` apropriado, em substituição ao menu que há agora: 

![screen shot 2017-12-20 at 15 05 35](https://user-images.githubusercontent.com/3904166/34219120-50a48e98-e597-11e7-9dde-eb5ca4a84cc6.png)

**Comment by kalimar** [comment]
Esse menu todo aí precisa de um LOVE. ❤️ 
Recomendo usar o menu do sistema de CSS que resolvermos usar.

**Comment by greevin** [comment]
Como a opção 'Sobre' foi para a aba junto com o 'Principal', não é necessário ter um menu. Caso eu queira voltar pra tela inicial, quando eu clicar em um polo ou um IPES, eu posso utilizar a seta do lado esquerdo do nome.
![ipes](https://user-images.githubusercontent.com/7833013/37559257-99b8dd7e-2a01-11e8-9f2d-675f90ac1655.png)
