### ISSUE TITLE
Substituir layer traçado por layer do mapbox

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#51]
Atualmente temos vários layers disponíveis para seleção pelo usuário. 

Criamos um traçado porque antigamente não tínhamos dados confiáveis de GPS. Ele tem 1mb, muito pesado, e pode ser removido agora como opção.

Queremos selecionar um layer bacana e clean do Mapbox que seja o default (substituindo o OSM - "Mapa Político").

É importante manter a seleção de polos e Núcleos (IPES) que já existe.

![screen shot 2018-01-05 at 17 34 11](https://user-images.githubusercontent.com/3904166/34625110-ad95c596-f23e-11e7-8979-d5945006f24f.png)

**Comment by gabrielfedel** [comment]
@tamielbr não seria legal a gente definir qual layer do mapbox queremos?

**Comment by tamielbr** [comment]
@gabrielfedel penso que por hora algo simples, como o ``basic`` ou o ``light`` (que é tons de cinza) mas o desenvolvedor pode definir. depois, podemos (eu faria isso com prazer) customizar detalhes no mapbox studio. acho que o mais importante é definir como layer principal e deixar isso pronto (keys do leaflet, etc.)

**Comment by gabrielfedel** [comment]
@tamielbr ótimo!

**Comment by kalimar** [comment]
https://www.mapbox.com/mapbox-gl-js/example/filter-markers/

**Comment by greevin** [comment]
Conforme solicitado, realizei a mudança para o Mapbox e selecionei, por ora, o layer 'Light' onde eu alterei no Mapbox Studio a língua para mostrar os países em português e a cor do oceano (oceano cinza fica muito estranho). Além disso, deixei implementado o menu com as opções para 'Núcleos' e 'Polos'.

![localhost_8080_](https://user-images.githubusercontent.com/7833013/37313357-98b719b8-262d-11e8-85a9-069c94e2dba9.png)
