### ISSUE TITLE
Melhoria de CSS geral

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#52]
Menu (barra esquerda) precisa de padronização e melhoria geral. 
Adequação de fontes/cores (geral).
- [x] Arredondar os cantos do popup. 
~~Evitar word-wrap desnecessário.~~
~~Aumentar distância entre o X e o texto do Popup.~~

Certamente veremos melhoria usando um sistema de CSS.

**Comment by kalimar** [comment]
http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3 - pra ajudar com cores.

**Comment by kalimar** [comment]
Acho que precisamos definer melhor o que são "melhorias". 
Quanto a padronização, utilização de algum sistema de CSS resolve isso. Assembly, tachyons. etc.

**Comment by kalimar** [comment]
- [x] Arredondar os cantos do popup. 
~~Aumentar distância entre o X e o texto do Popup.~~

**Comment by greevin** [comment]
Com o 'mouseenter' e o 'mouseleave' ainda é necessário ter um X para fechar o popup?

**Comment by kalimar** [comment]
Concordo, não faz sentido

**Comment by greevin** [comment]
Adicionei um border-radius de 7px (o padrão do Mapbox é 3px).

![pop](https://user-images.githubusercontent.com/7833013/37526287-b3321dfa-290d-11e8-88a6-e667d8fb933e.png)

Como comentando, acho que não precisa do X para fechar o popup, já que agora o popup some quando move o mouse.
