### ISSUE TITLE
Definir padrão do CSV para ser importado

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#53]
Definir padrão do CSV para ser importado e utilizado na visualização do mapa

**Comment by tamielbr** [comment]
@gabrielfedel avaliando JSON, #57.

**Comment by tamielbr** [comment]
Fechado conforme modelo de @gabrielfedel, usamos 3 json.

**Comment by gabrielfedel** [comment]
Definido nos seguintes modelos:

https://github.com/educacaoaberta/CiclopeDB/blob/master/data/update/PolosIES_limp.csv
https://github.com/educacaoaberta/CiclopeDB/blob/master/data/update/ipes-insert.csv
https://github.com/educacaoaberta/CiclopeDB/blob/master/data/update/polos-insert.csv
