### ISSUE TITLE
Definir tipos de filtragem do datatables

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#55]
Definir que tipos de filtragens estarão disponíveis no datatables que irão atualizar os gráficos

**Comment by tamielbr** [comment]
Se o usuário clica numa IPES, a aba deve mostrar: 
1. Tabular: a lista de polos associadas à IPES clicados, seus estados e ao final, o número total de polos
2. Gráfico: número de IPES associadas, por estado (o sistema tem uma implementação dessa funcionalidade) 

Se o usuário clicar num polo, a aba deve mostrar:
1. Tabular: a lista de IPES associadas ao polo clicado, e seus estados, e ao final, o número total de IPES
2. Gráfico: número de IPES associadas, por estado  (o sistema tem uma implementação dessa funcionalidade)

**Comment by tamielbr** [comment]
@gabrielfedel - Já discuti isso no #56, veja se está ok? Podemos pensar em eliminar os gráficos se a implementação (que depende, creio, de integração com ``datatables``) seja pesada. Se achar ok, pode fechar essa.

**Comment by gabrielfedel** [comment]
Ok! vou encerrar!
