### ISSUE TITLE
Display de dados tabulares para cada ponto clicado

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#56]
Atualmente o sistema indica os polos no mapa (pino em forma de círculo indicando essa relação) mas queremos os mesmos dados de forma textual, na aba para que seja clara a listagem de nomes dos polos. Depende de #55. 

Ao clicar em uma IPES ou polos, janela de informações sempre tem duas abas. A primeira tem os dados descritivos (cidade, telefone, etc.). 

A segunda aba na janela é um ``datatables`` contendo uma tabela que puxa todos os dados do JSON referente àquela IPES ou polo que foi clicado (_o sistema de abas já está implementado mas pode ser modificado_).

Se clicar numa IPES a aba com ``datatables`` deve mostrar dados de todos os polos relacionados:
- Nome do polo
- Estado
A última linha do datatables deve mostrar totais e depois, um gráfico em barra dinâmico que mostre os resultados (número de polos por estado).

Se clicar num polo a aba com ``datatables`` deve mostrar todos os dados de todas as IPES relacionadas:
- Nome da IPES
- Estado
A última linha do datatables deve mostrar totais e um gráfico em barra dinâmico que mostre os resultados (número de IPES por estado).

**Comment by kalimar** [comment]
Já tá implementado aqui https://github.com/educacaoaberta/CiclopeDB/pull/62  @tamielbr?

**Comment by tamielbr** [comment]
@greevin eu creio que isso já terminou com sua implementação atual no #62, correto?

**Comment by greevin** [comment]
Não, isso se refere ao DataTables dos polos e IPES separados quando se clica em um ponto. O único DataTables que está implementado é da página inicial se refere uma lista só.
![ciclopedb test_ laptop with mdpi screen](https://user-images.githubusercontent.com/7833013/36846901-47cf8eae-1d3b-11e8-956d-07d4429ff92c.png)

**Comment by greevin** [comment]
Ao clicar em um IPES, ele agora tem a aba 'Dados' com o gráfico e o DataTables dos polos por estado.
![polos](https://user-images.githubusercontent.com/7833013/37555655-b19bff30-29c9-11e8-8b29-63a6bc7267bb.png)

O mesmo está acontecendo com os polos que agora mostra o gráfico e o DataTables dos IPES por estado.
![ipes](https://user-images.githubusercontent.com/7833013/37555657-c5c4bd3a-29c9-11e8-8b1f-b8a2648e13d3.png)
