### ISSUE TITLE
Voltar Ciclope para uso de Json ao invés de DB

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#57]
Tendo em vista que o uso de dados vai ser menor, não há necessidade de manter a estrutura de banco de dados. Vamos voltar ao modelo original do ``Ciclope`` (http://github.com/tamielbr/Ciclope) que usava só Json - mas partindo do código mais novo na base do ``CiclopeDB``.

**Comment by gabrielfedel** [comment]
Depende do Issue #58

**Comment by gabrielfedel** [comment]
Com o formato do json definido (issue #58) a ideia dessa issue é que o sistema funcione exatamente como funciona hoje (incluindo as novas funcionalidades da issue #56) utilizando arquivos json (que seguirão o modelo disponível em: https://github.com/gabrielfedel/CiclopeDB/blob/json/json/ipes_test.json e 
https://github.com/gabrielfedel/CiclopeDB/blob/json/json/polos_test.json )

Sugestões de mudança no modelo de json são bem vindas.

**Comment by kalimar** [comment]
Coloquei um comentário no #58 .

**Comment by tamielbr** [comment]
@greevin podemos fechar, não? Agora já temos o #58 pronto.
