### ISSUE TITLE
Definir formato dos json que serão armazenados

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#58]
Definir formato, principalmente referente à como relacionar ipes e polos

**Comment by tamielbr** [comment]
@gabrielfedel fazendo testes no JSON até 07/01.

**Comment by gabrielfedel** [comment]
Minha proposta é ter 2 json, conforme os seguintes exemplos:
https://github.com/gabrielfedel/CiclopeDB/blob/json/json/ipes_test.json
https://github.com/gabrielfedel/CiclopeDB/blob/json/json/polos_test.json

Os dados vão ficar redundantes, mas imagino que é o esperado e deve deixar a visualização rápida.
Nesse modelo podemos trocar o json local por uma api remota que retorna esses dados.

**Comment by tamielbr** [comment]
@gabrielfedel como conversamos já, acho que você pensou que nesse caso, considerando os dados que recebemos da fonte, precisamos dessa redundância extra. eu achava que conseguiríamos um JSON só e faríamos os queries, mas realmente isso pode ser muito custoso para uma implementação tão simples. 

1. o ``ipes_by_state`` e ``polos_by_state`` - precisamos fazer isso hard coded? Não seria melhor fazê-lo dinâmico? Me parece um loop fácil.
2. o ``UF`` podia padronizar (maiúsculo ou minúsculo).

**Comment by gabrielfedel** [comment]
1. Acho que dá pra fazer sim (entraria na conta da issue #57 )
2. Opa sim.

Vou atualizar os exemplos de json, e vou atualizar a descrição da issue #57

**Comment by kalimar** [comment]
Queria entender melhor porque precisam de dois arquivos JSON. É pra facilitar algo no datatables? Creio que para o mapa não seja necessário.

Se for só para o mapa acho que poderia ser o seguinte:
```
{
  "type": "FeatureCollection",
  "features": [{
      "geometry": [-48.4887684, -1.4302111],
      "type": "Feature",
      "properties": {
        "id": "1a", // esse campo é importante?
        "url": null,
        "cidade": "acrelandia",
        "tipo": "polo",
        "polo": "acrelandia",
        "sigla" "UEPA"
      }
    },
    {
      "geometry": [-48.4887684, -1.4302111],
      "type": "Feature",
      "properties": {
        "id": "1b",
        "URL": "http:foo.com",
        "cidade": "Belem",
        "tipo": "ipes",
        "polo": "acrelandia",
        "sigla": "UEPA"        
      }
    }
  ]
}
```

Deixaria-se os campos desnecessários nulos e identificaria o tipo de ponto como Polo ou IPES.

**Comment by gabrielfedel** [comment]
Olá Kalimar,
o grande motivo foi que existe uma relação n-m entre ipes e polos (1 polo pode pertencer a diversos ipes, e 1 ipes pertencer a diversos polos). Dessa forma o jeito que me pareceu ser o mais "rápido" para ser processado era ter dados redudantes nos 2 json. 

Imagino que exista um jeito melhor, se tiverem sugestões são bem vindas!

**Comment by greevin** [comment]
Eu criei uma View no banco de dados para que ele pudesse pegar as informações dos polos e dos ipes junto com a sua nome, a cidade e o estado para utilizar no DataTable na página 'Dados'. Convertei ela pro Geojson e que ficou assim: 

```
"type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "tipo": "polos",
        "nome": "ACRELANDIA - CENTRO",
        "cidade": "Acrelândia",
        "estado": "AC"
      },
      "geometry": null
    },
```

**Comment by tamielbr** [comment]
Seguimos com 3 JSONs
1 - polos
2 - ipes
3 - relação
@gabrielfedel vai criar um script assumindo o formato de dados que recebemos agora da capes.

**Comment by tamielbr** [comment]
Fechado conforme modelo feito por @gabrielfedel.
