### ISSUE TITLE
Substituir página principal por abas

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#59]
O sistema hoje tem um menu com duas páginas (``principal`` e ``sobre``).

Queremos que isso seja uma única página ``principal`` com os mesmos conteúdos, só que em três abas (veja relação com #50):

1. Principal
2. Sobre o projeto
3. Dados

**Principal** 

Manteremos a linha do tempo (que usa o ``timeline.js``) como está. Para os gráficos, precisamos de algumas alterações. Primeiro, todos os gráficos do sistema precisam estar em gráficos de barra - vamos eliminar o uso de gráficos de torta, portanto:

1. _Ajuste_ -> O número de IPES por estado, em gráfico de barra. Precisamos adicionar em algum lugar o número do total de IPES - isso não é visível. Talvez no título?
2. _Ajuste_ -> O número de IPES por região geográfica, mudar pra barra.
3. _Novo gráfico_ -> O total de polos por estado ao invés de região geográfica, em gráfico de barra.  Precisamos adicionar em algum lugar o número do total de IPES - isso não é visível. Talvez no título?
4. _Novo gráfico_ -> O número de polos por região geográfica, mudar pra barra.

**Sobre**

Manter como está. Depois posso fazer ajuste no conteúdo.

**Dados**
A ideia aqui é representar os dados que temos no mapa em formato de tabela, um ``datatables`` com alguns dos dados disponíveis para que as pessoas possam fazer buscas com facilidade.

1. Tipo (IPES ou polo)
2. Nome (se for IPES, é a sigla da universidade - se for polo normalmente é nome de cidade)
3. Cidade
4. Estado

A medida que o usuário filtra os dados (usando o ``datatables``), a linha final deve ter a contagem dos resultados atualizados.

**Comment by kalimar** [comment]
Esse issue fecha aqui com esse PR? https://github.com/educacaoaberta/CiclopeDB/pull/62 @tamielbr

**Comment by tamielbr** [comment]
Me parece que sim, não falta nada vc fecha aqui @greevin?

**Comment by greevin** [comment]
Não falta mais nada. Vou fechar.
