### ISSUE TITLE
Inserir dados completos do NEAD no CiclopeDB

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#6]

**Comment by gabrielfedel** [comment]
@tamielbr estou acertando os dados dos cursos para inserir, porém encontrei alguns associados à IES's que não temos cadastrados, como o Fiocruz

Sabe se existem mais IES's não cadastrados ?

**Comment by gabrielfedel** [comment]
Quando digo não cadastrados, digo na versão atual do sistema. Pensando agora também fiquei em dúvida se isso já era algo esperado (ter novas IPES, que não estava cadastradas)

**Comment by tamielbr** [comment]
@gabrielfedel não temos cadastrados onde? naquele mapa das IES? (que tem as 95)?

**Comment by gabrielfedel** [comment]
@tamielbr , opa me confundi, é que no mapa dos polos não tinham todas
vou converter os dados do mapa da ies para o formato dos dados do mapa dos polos

**Comment by gabrielfedel** [comment]
Modificar para usar o id da capes
