### ISSUE TITLE
Subir dados 2018 para o sistema até 15/jan

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#60]
A pedido da CAPES.

**Comment by gabrielfedel** [comment]
Em andamento, aguardando dados das ipes para finalizar. Branch updatedb já contém as modificações de código necessário.

**Comment by gabrielfedel** [comment]
Feito.
Foi necessário diversas correções manuais.
Pode ser interessante criar uma api no futuro que à partir dos csv crie um banco de dados e disponiblize consultas em formato json
