### ISSUE TITLE
Tratamentos de UX

### ISSUE THREAD

**Issue by kalimar** [gabrielfedel/CiclopeDB#66]
- [x] Nome do Polo ou do IPES deve aparecer com "mouse enter" e desaparecer com "mouse leave"
- [x] Tratamento consistente do pointer: Mão apontando quando se entra em algo clicavel, Ou mão aberta OU flecha quando não se pode clicar. Atualmente Temos as três possibilidades.
- [x] Administrar o tamanho dos círculos para que não se sobrepõem. Utilizar clusters e/ou tamanhos que mudam dinamicamente com zoom.
~~Clicar em area do mapa que não tem ponto fecha o painel da direita.~~
- [x] Polos e Ipes devem ter a mesma ação quando se clica - Mostrar o painel primeira vez que se clica num ponto, mudar conteúdo do painel se usuário clica em ponto novo, ou fechar o painel se usuário clica no mesmo ponto. Pessoalmente, não sei se gosto da experiência do painel fechar quando se clica no ponto. O que vocês acham? Prefiro fechar o painel só quando clico no X. É muito movimento para mim.
~~tooltip explicando para que é o icone no menu principal.~~
- [x] click area dos polos parece que está grande e nem sempre permite clicar nos ipes próximos.

**Comment by gabrielfedel** [comment]
Acho uma boa fechar o painel somente quando se clica no X

**Comment by kalimar** [comment]
Parece que o "mouseleave" está acontecendo nos pontos principais (os polos?) e não nos pontos mentores (ipes?). Desculpe ainda não consigo lembrar qual é qual.

**Comment by greevin** [comment]
Os pontos que aparecem na tela inicial (com o pin azul) são os IPES. Os círculos são os polos. Testei aqui e o 'mouseleave' tá funcionando para os dois.

**Comment by tamielbr** [comment]
Acho que vale estilizar os polos com algo mais simpático do que há agora. Os pins dos IPES ficaram legais, mas o dos polos é antigo ainda.

**Comment by greevin** [comment]
Como sugestão, podemos usar os ícones que são disponíveis pelo Mapbox: https://www.mapbox.com/maki-icons/. Subi uma versão pro servidor com uma sugestão para o ícone do polos.

**Comment by tamielbr** [comment]
Gostei do ícone! Mas o cinza fica bem difícil de ver. (polos)

**Comment by kalimar** [comment]
Fácil fazer outra cor. Se tiver dúvida me avisa. O gerador de icone é meio
confuso (pra mim pelo menos)

**Comment by greevin** [comment]
Alterei a cor do ícone no editor do Maki Icons e subi o novo ícone no Mapbox Studio. Com a cor preta (#000) ficou muito ruim e tive que colocar um cinza mais escuro (#404040).
