### ISSUE TITLE
Polos permanecem na visualização mesmo que todos polos sejam desselecionado 

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#68]
Quando entro no mapa, clico numa IPES, aparecem os polos.

Quando vou ao menos e seleciono para mostrar todos os polos e depois não mostrar nada, os polos originais da IPES permanecem.

Vídeo -> [persistencia_polos.zip](https://github.com/educacaoaberta/CiclopeDB/files/1832996/persistencia_polos.zip)

**Comment by greevin** [comment]
Corrigido. Ao clicar em 'Polos', ele mostra todos os polos e ao desmarcar, ele some com todos, inclusive os que aparecem quando clicado em um IPES para mostrar.
