### ISSUE TITLE
Inserir dados LAT/LON para polos na tabela

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#7]
http://cep.correiocontrol.com.br/02011200.json

**Comment by gabrielfedel** [comment]
@tamielbr a maior parte dos CEP's disponíveis é um cep da cidade inteira
Pegamos lat/long da cidade mesmo? ou vamos atrás de um jeito de pegar pela rua?

**Comment by tamielbr** [comment]
Se der pra investigar mais um pouco ,seria legal saber se tem algum outro jeito. Pode fazer queries no mapbox por exemplos... não sei qual o melhor esquema. Te passo um email dum cara que possa ajudar.

**Comment by gabrielfedel** [comment]
Ví o email que mandou pro Peter, mas o problema na verdade não era a busca por lat/long, e sim que os CEP's na base eram CEP's da cidade, e não da rua em sí.
Mas pelo que olhei agora, boa parte das ruas não tem CEP (pelo menos não encontrei no correio), então sigo com o lat/long do CEP mesmo (apontando pra cidade), ou buscamos outro jeito?

**Comment by tamielbr** [comment]
Ah, acho que seguimos com o que o CEP indicar. Se ele tiver 8 digitos, ele tem que ser bem específico (rua). Agora se tem 5 + 000 (ou nada), realmente podemos apontar só pra cidade.

**Comment by gabrielfedel** [comment]
é, vários deles está somente com 5 + 000, mas vários dos casos que verifiquei é devido ao fato de não ter cep mesmo nas ruas. 
Então vou seguir usando o quê os CEP's indicarem

**Comment by gabrielfedel** [comment]
Só pra comentar, o jeito que encontrei é usando o google maps mesmo

Sobrando tempo vou buscar outros caminhos pra conseguir o lat long à partir do CEP (provavelmente combinando alguns serviços)

**Comment by gabrielfedel** [comment]
Inserido parcialmente, o google não conseguiu achar o posicionamento de uns 100 pontos, precisa ser revisado manualmente

**Comment by gabrielfedel** [comment]
modificar o script para usar logradouro quando o cep não funcionar
