### ISSUE TITLE
Script de atualização de Dados

### ISSUE THREAD

**Issue by gabrielfedel** [gabrielfedel/CiclopeDB#70]
Criar script para receber novos dados da CAPES.
Esse script precisa fazer as seguintes operações:

- verificar se um dado já existe ou é novo (só é inserido dado novo)
- se for dado novo verificar se existe o lat/lng
- se não existir possivelmente procurar em alguma api (mapbox?)
- pedir para o usuário confirmar se a posição está correta

**Comment by tamielbr** [comment]
@kalimar é possível implementar isso o com API do mapbox (search) ou temos que usar outra coisa? no passado, por conta do problema de endereços incompletos, buscamos por cidade. Mas acho que, @gabrielfedel , teremos um problema dessa vez, porque em alguns casos temos dados muito precisos, e fica estranho usar dados "aproximados" para alguns e não para outros, sem deixar isso claro pro usuário. 

Sugestão: se não houver ``lat/lon`` fazer a busca automática com base em endereço ou só cidade, e ter alguma anotação nos dados (endereço), com um _append_ talvez, que indique que o endereço é ``aproximado``?

Esse ``pedir para o usuário`` seria uma forma de feedback no próprio mapa? Seria legal...

**Comment by gabrielfedel** [comment]
Eu pensei nesse script "offline", só para atualização dos dados (assim como é o de conversão csv -> json, na verdade a ideia é unificar em um único script).

**Comment by gabrielfedel** [comment]
@tamielbr não entendi o que disse que é problema. Os precisos são os dados que já temos cadastrados certo? E os aproximados seriam os novos, é isso?

Imagino que a solução seja ter algum campo nos dados que são visualizados que indiquem que é aproximado (imagino que seja necessário modificar a visualização)

**Comment by tamielbr** [comment]
Sim - o problema é que precisamos que o usuário saiba quando o ponto é preciso e correto (fornecido pela CAPES) ou quando ela é estimado (API). pode ser na visualização, mas talvez para não complicar no design, poderia ser algo que apareça no endereço, um append automático do script:

![screen shot 2018-04-03 at 14 07 27](https://user-images.githubusercontent.com/3904166/38264247-ce1d83fe-3748-11e8-8b72-abd7308af718.png)

por exemplo ao invés do que está aqui, seria: Transcontinental, 437 (**Endereço estimado automaticamente, não fornecido pelo polo**) ou similar...

**Comment by gabrielfedel** [comment]
Show, assim é bem tranquilo e pode entrar no próprio script.

**Comment by tamielbr** [comment]
@gabrielfedel to aguardando retorno da CAPES com os dados. Você acha demorado o script? Só pra organizar o deploy final do sistema e prazos.

**Comment by gabrielfedel** [comment]
então, não deve ser muito demorado de fazer, mas depende um pouco dos dados da CAPES. Imagino que a cada nova inserção de dados vão aparecer casos novos de dados inconsistentes para serem tratados.


@tamielbr sua ideia é inserir esses dados para a apresentação de amanhã? Se sim, talvez seja melhor fazer sem o script. De todo modo vou tentar trabalhar nele hoje à noite

**Comment by tamielbr** [comment]
@gabrielfedel duvido que consigamos os dados tão rápido, então não penso em trabalhar com essa possibilidade. Mas creio que conseguiremos para semana que vem e assim conseguiríamos fechar de vez. A ideia é dar um prazo para que eles naveguem (3-4 dias) e fechemos.

**Comment by gabrielfedel** [comment]
blz, ótimo. Eu acho que vou esperar eles mandarem os dados pra fazer o script, pois assim vou ter certeza (ou quase) de como virá nas próximas vezes

**Comment by tamielbr** [comment]
Conforme me foi informado hoje, @gabrielfedel teremos isso até 5/maio.

**Comment by gabrielfedel** [comment]
Ótimo! fico no aguardo ;)

**Comment by gabrielfedel** [comment]
@tamielbr , estou trabalhando no script e queria confirmar com você qual vai ser a abordagem para inserir dados novos:
-se na tabela atualizada de ipes ou polos não existir um item que existia antes, esse item deve ser removido?
-se for um item que já existe vou manter os dados antigos (por causa do lat/log)
-se for um item novo, adiciona-lo

é isso mesmo?

**Comment by tamielbr** [comment]
@gabrielfedel assumimos que os dados que foram fornecidos são totais e atuais, portanto penso que sim:
* se entrada não existe, insere
* se entrada existe, atualiza dados existentes - acho perigoso manter dados antigos porque relação IPES-polo pode ter mudado. Mas se a entrada nova não tem lat/lon, atualizamos tudo menos lat/lon para que ao menos tenhamos nossa estimativa, e por isso...
* ... para entradas sem lat/lon, que buscamos via API (novas ou antigas) mantemos os dados estimados e indicamos ao usuário que foi **estimado** (conforme discutimos acima)
* se item existe na _nova_ e não na _antiga_, deve ser removido, o que significa que provavelmente o polo ou IPES não é mais parte do sistema (duvido que aconteça com IPES mas pode certamente ocorrer com descredenciamento de polo)

**Comment by gabrielfedel** [comment]
@tamielbr especificamente para o caso que a entrada nova tem lat/long, os dados antigos que temos de lat/long não são mais precisos que os passados pela CAPES ?

**Comment by tamielbr** [comment]
Eu assumo que os dados da CAPES serão sempre mais precisos.

**Comment by tamielbr** [comment]
@gabrielfedel podemos fechar? Te pediria pra colocar o script na base do código e alguma documentação por favor, eu mesmo preciso saber fazer isso depois. Valeu!

**Comment by tamielbr** [comment]
@gabrielfedel podemos fechar? documentação online?

**Comment by gabrielfedel** [comment]
Opa tel, eu ainda quero fazer um teste com busca "automática" de lat/lng, não consegui fazer pois nesses dados não aconteceu de ter um ponto sem que a gente já não tivesse. 

Vou tentar fazer isso até o fim de semana, aí eu subo uma documentação junto com o script (e fecho aqui)

**Comment by gabrielfedel** [comment]
@tamielbr Já criei um pull request com o script, porém não consegui bons resultados com a busca automática de endereço. Não consegui usar a api do mapbox para fazer uma busca por bairro, e por rua não são todos os ipes/polos que tem um endereço válido (ou "encontrável").

Acho que precisamos refinar como vamos procurar quando não tiver endereço, pensar em uma "heurística", talvez o @kalimar possa nos dar alguma sugestão.

Minha ideia é fechar esse issue, e abrir um específico pra isso. O script do jeito que está agora só faz o merge para dados com lat/lng.

**Comment by kalimar** [comment]
O api de busca falta um pouco de aprimoramento. Se quiserem tentar, podemos agendar uma hora pra descutir o que querem fazer. Essa semana vai ser impossível estarei viajando a trabalho e bastante atarefado.

**Comment by tamielbr** [comment]
@gabrielfedel concordo em abrir outro issue com 'Wishlist' e fechar esse.

**Comment by gabrielfedel** [comment]
Feito. Encerrando essa issue.
