### ISSUE TITLE
Problema na interação entre mostra polos e busca

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#72]
(Mandei por vídeo/telegram).

Quando faço uma busca e mostro todos os polos (clicando na opção no menu), eles não aparecem.

**Comment by greevin** [comment]
Subi a modificação, agora ele mostra todos os polos quando você marca a opção no menu das camadas, mas ao desmarcar ele some com todos os polos e, caso seja necessário visualizar os polos associados a um IPES tem que clicar no IPES de novo.

**Comment by tamielbr** [comment]
Acho melhor assim.
