### ISSUE TITLE
Linha do tempo com erro

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#73]
Todos os itens estão aparecendo visualmente no mesmo lugar, sem uma linha do tempo efetivamente.

A primeira (página principal está ok). A das IPES é que tem problema.

![screen shot 2018-04-05 at 09 11 32](https://user-images.githubusercontent.com/3904166/38365103-6c6b22e6-38b1-11e8-9f45-dc6a6d8745a7.png)
![screen shot 2018-04-05 at 09 04 30](https://user-images.githubusercontent.com/3904166/38365105-6dbe9db2-38b1-11e8-9494-7ecb2009a2bd.png)

**Comment by greevin** [comment]
O plugin não funciona direito em abas que ficam escondidas (por isso que na página 'Principal' ela está funcionando corretamente) e a solução encontrada foi adicionar a timeline na primeira aba, remover e adicionar para a aba correta.

**Comment by tamielbr** [comment]
ok, quebra um galho. vamos manter. não sei se usaremos no futuro, mas pelo menos fica o demo.
