### ISSUE TITLE
Incluir "X" para fechar janela na principal

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#74]
Tá assim:

![screen shot 2018-04-05 at 09 12 50](https://user-images.githubusercontent.com/3904166/38365146-95b0f1f8-38b1-11e8-95ce-b5db4d535230.png)

Mas acho bom ficar como nas outras para permitir que o usuário consiga ver o mapa todo se quiser, do modo como tá nas outras páginas:

![screen shot 2018-04-05 at 09 12 58](https://user-images.githubusercontent.com/3904166/38365144-94c69388-38b1-11e8-92e1-810b0f2d2e72.png)

**Comment by greevin** [comment]
Feito.
