### ISSUE TITLE
Jogar dados da página principal para a aba DADOS

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#75]
Como é com as outras página internas, os gráficos podem ficar logo abaixo do ``datatables``, agora ela está na primeira aba abaixo do texto.

![screen shot 2018-04-05 at 09 14 24](https://user-images.githubusercontent.com/3904166/38365194-c2dc42c2-38b1-11e8-9573-a94c63746801.png)

**Comment by greevin** [comment]
Feito.
