### ISSUE TITLE
Dados dos cursos

### ISSUE THREAD

**Issue by ghost** [gabrielfedel/CiclopeDB#80]
eu acho que achei a resposta do que perguntei das outras 3 issues https://github.com/educacaoaberta/CiclopeDB/issues/77 , https://github.com/educacaoaberta/CiclopeDB/issues/78 , https://github.com/educacaoaberta/CiclopeDB/issues/79 . é isso?

https://github.com/educacaoaberta/CiclopeDB/blob/master/model/cursos.php

Talvez seja o caso só de colocar no readme :)

**Comment by ghost** [comment]
(aparentemente tudo que eu perguntei já tem, o que falta são os dados, é isso?)

**Comment by tamielbr** [comment]
Sim. Como ele não foi ainda lançado, não atualizamos os dados nem o Readme. Boa dica.
