### ISSUE TITLE
Adaptação dos script para geração de dados/gráficos com base em JSON

### ISSUE THREAD

**Issue by tamielbr** [gabrielfedel/CiclopeDB#82]
Com base no feito em #70, criar scripts que convertam os dados necessários para o resto do sistema (em andamento). Depois documentar o processo e inserir scripts num folder (talvez todos num só, @greevin?).

**Comment by tamielbr** [comment]
@greevin podemos fechar? documentação no GitHub ok?

**Comment by greevin** [comment]
@tamielbr Sim, acho que podemos fechar. Coloquei uma descrição no README lá (https://github.com/greevin/CiclopeDB/tree/feature/mapbox/src).
